services:

    # DEVELOPMENT override config
    example-app-laravel:
        build: 
            context: .
            target: development
        image: example-app/laravel-dev
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - LOG_LEVEL=debug
            - APP_KEY=
            - BROADCAST_DRIVER=null
            - DB_PASSWORD=
            - LOG_RETENTION_DAYS=1
        volumes:
             - './source:/app'

    # PRODUCTION override config
    # example-app-laravel:
    #     build: 
    #         context: .
    #         target: production
    #     image: example-app/laravel-prod
    #     environment:
    #         - APP_ENV=production
    #         - APP_DEBUG=false
    #         - APP_KEY=
    #         - BROADCAST_DRIVER=null
    #         - DB_PASSWORD=
    #         - LOG_RETENTION_DAYS=14
    
    example-app-pgsql-db:
        environment:
            - PGPASSWORD=
            - POSTGRES_PASSWORD=
